### ISSUE TITLE
AttributeError: module 'mxnet' has no attribute 'mod'

### ISSUE THREAD

**Issue by antonnes** [ai-forever/ghost#56]
Trying to run the repo on Windows 10.
Installed mxnet-cu102-2.0.0b20201108. 

The code execution stops on line 115 in image_infer.py file
` model = mx.mod.Module(symbol=sym, context=ctx, label_names=None)`

Full error: AttributeError: module 'mxnet' has no attribute 'mod'

**Comment by antonnes** [comment]
Actually made it work with version `mxnet_cu102-1.7.0-py2.py3-none-win_amd64.whl`
Used the following install command 
`pip install mxnet_cu102==1.7.0 -f https://dist.mxnet.io/python/cu102`
